name: CI/CD for Hospital System

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Check out del repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # Paso 2: Configurar JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    # Paso 3: Construir la imagen Docker
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/hospital-app:latest .

    # Paso 4: Iniciar sesión en Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Paso 5: Push de la imagen a Docker Hub
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/hospital-app:latest

    # Paso 6: Desplegar en el servidor de producción
    - name: Deploy to Production Server
      run: |
        ssh user@localhost 'docker pull ${{ secrets.DOCKER_USERNAME }}/hospital-app:latest && docker run -d --name hospital-app -p 8080:8080 hospital-app:latest'
