name: Java CI and Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Check out del repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # Paso 2: Build y Test
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Build Docker image
      run: docker build -t hospital-app .

    # Paso 3: Correr el contenedor
    - name: Run Docker container
      run: docker run -d --name hospital-app hospital-app
